blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/orgs/community/discussions/categories/copilot
    about: Please ask and answer questions about GitHub Copilot here
